### ISSUE TITLE
make support for mysql dependencies

### ISSUE THREAD

**Issue by torsteinelv** [Super-Visions/docker-itop#22]
Just example,

add to chart:
```yaml
dependencies:
  - name: mysql
    version: 9.10.0 
    repository: https://charts.bitnami.com/bitnami
```

add to values:
```yaml
mysql:
  enabled: true
  auth:
    rootPassword: your-root-password
    database: itop
    username: itop
    password: your-password
  primary:
    persistence:
      enabled: true
      size: 10Gi
```

add to templates/deployment.yaml:
```yaml
env:
  - name: DB_HOST
    value: {{ .Release.Name }}-mysql
  - name: DB_USER
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-mysql
        key: username
  - name: DB_PASSWORD
    valueFrom:
      secretKeyRef:
        name: {{ .Release.Name }}-mysql
        key: password
  - name: DB_NAME
    value: itop
```

**Comment by Hipska** [comment]
Good idea, however since Combodo recommends to use MariaDB over MySQL, I would add that as dependency instead. And preferable also the official MariaDB container. PRs are welcome.

**Comment by torsteinelv** [comment]
Not sure how to create an pr on this.

we can change to chart.yaml
```yaml
dependencies:
  - name: mariadb
    version: ~18.2.4
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled


values:
mysql:
  enabled: true
  auth:
    rootPassword: itop
    database: itop
    username: itop
    password: itop
  primary:
    persistence:
      enabled: true
      size: 10Gi
```
