### ISSUE TITLE
issue after deployed

### ISSUE THREAD

**Issue by torsteinelv** [Super-Visions/docker-itop#23]
Any reason why Im not reggiting this service started?

```
root@k8s-m1:~# kubectl logs itop-itop-chart-64dc655875-42btf -n itop
tail: cannot open 'log/setup.log' for reading: No such file or directory
tail: cannot open 'log/error.log' for reading: No such file or directory
tail: cannot open 'log/deadlocks.log' for reading: No such file or directory
tail: cannot open 'log/deprecated-calls.log' for reading: No such file or directory
tail: cannot open 'log/tools.log' for reading: No such file or directory
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.3.198. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.42.3.198. Set the 'ServerName' directive globally to suppress this message
[Tue Nov 26 12:08:01.475049 2024] [mpm_prefork:notice] [pid 1:tid 1] AH00163: Apache/2.4.62 (Debian) PHP/8.3.11 configured -- resuming normal operations
[Tue Nov 26 12:08:01.475476 2024] [core:notice] [pid 1:tid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
10.42.3.1 - - [26/Nov/2024:12:08:02 +0000] "GET /webservices/status.php HTTP/1.1" 500 309 "-" "kube-probe/1.31"
10.42.3.1 - - [26/Nov/2024:12:08:03 +0000] "GET /webservices/status.php HTTP/1.1" 500 309 "-" "kube-probe/1.31"
10.42.3.1 - - [26/Nov/2024:12:08:10 +0000] "GET /webservices/status.php HTTP/1.1" 500 309 "-" "kube-probe/1.31"
10.42.3.1 - - [26/Nov/2024:12:08:10 +0000] "GET /webservices/status.php HTTP/1.1" 500 309 "-" "kube-probe/1.31"
root@k8s-m1:~#
```

**Comment by torsteinelv** [comment]
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itop
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Super-Visions/docker-itop.git
    targetRevision: "3.2.0"
    path: 'helm-chart'
    helm:
      values: |
        service:
          type: LoadBalancer
          port: 80
          targetPort: 80
        image:
          repository: "supervisions/itop"
          tag: "3.2.0"  # Updated to a specific tag for stability
          pullPolicy: IfNotPresent  # Improved performance for stable images
        pvc:
          accessMode: ReadWriteOnce
          storageClassName: "csi-rbd-sc"
        environment:
          db_host: "itop-mariadb"  # MariaDB-tjenestens navn
          db_name: "itop"          # Database som brukes av iTop
          db_pwd: "secure-password"  # Oppdatert passord for sikkerhet
          db_user: "itop-user"       # Dedikert bruker for iTop

        ingress:
          enabled: false
          className: "nginx"
          annotations:
            external-dns.alpha.kubernetes.io/hostname: "itop.domain.com"
            external-dns.alpha.kubernetes.io/target: "nginx.domain.com"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            kubernetes.io/ingress.class: "nginx"
            nginx.ingress.kubernetes.io/proxy-body-size: "50m"
          hosts:
            - host: itop.domain.com
              paths:
                - path: /
                  pathType: ImplementationSpecific
          tls:
            - secretName: itop-cert
              hosts:
                - itop.domain.com
  destination:
    server: https://kubernetes.default.svc
    namespace: itop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: itop-mariadb
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: "18.2.4"
    chart: mariadb
    helm:
      values: |
        auth:
          rootPassword: "root-password"
          database: "itop"
          username: "itop-user"
          password: "secure-password"
        primary:
          persistence:
            enabled: true
            storageClass: "csi-rbd-sc"
            size: "8Gi"  # Juster størrelse etter behov
  destination:
    server: https://kubernetes.default.svc
    namespace: itop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
```

**Comment by torsteinelv** [comment]
when changing to, it starts as expected.
```
    repoURL: https://github.com/Super-Visions/docker-itop.git
    targetRevision: "3.2.0"
    helm:
      values: |
        image:
          tag: "3.0.0"  # Updated to a specific tag for stability

```
