### ISSUE TITLE
2.7/3.0 images broken/missconfigured?

### ISSUE THREAD

**Issue by lazyest** [Super-Visions/docker-itop#8]
Just started to use itop with your docker images. Few days I've spent on figuring out and now I see 2.7 and 3.0 images are not working as default. From my point thsts something wring with database connection, because on manual installation it shows empty page after wizard steps done and I have in logs

> mariadb             | 2023-04-03 12:59:20 34 [Warning] Access denied for user ''@'172.22.0.5' (using password: NO)
> mariadb             | 2023-04-03 12:59:24 35 [Warning] Access denied for user 'itop'@'172.22.0.5' (using password: NO)
> mariadb             | 2023-04-03 12:59:25 36 [Warning] Access denied for user 'itop'@'172.22.0.5' (using password: NO)
> mariadb             | 2023-04-03 12:59:54 43 [Warning] Access denied for user ''@'172.22.0.5' (using password: NO)
> mariadb             | 2023-04-03 12:59:56 46 [Warning] Access denied for user ''@'172.22.0.5' (using password: NO) 

User/pass is working and same docker-compose configuration for 2.6 image is working fine

Also I've tried unattended installation with wiki-provided sampled xml response file, same thing. Maybe I'm wrong but just now I have no another explanation

docker-compose part:
```yaml
  db:
    image: mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - ./mariadb:/var/lib/mysql
  itop:
    image: supervisions/itop
    container_name: itop
    restart: always
    depends_on:
      - db
```

Unattented mode seems to be non-compatible with 3.x in general
`docker-compose exec -T -u www-data itop bash -c "cd setup; php install.php --response_file=install.xml --clean=1"`

> Installation mode detected.
> Cleanup mode detected.
> Trying to delete the configuration file: '/var/www/html/conf/production/config-itop.php'.
> Emptying the cache directory '/var/www/html/data/cache-production'.
> Emptying the target directory '/var/www/html/env-production'.
> Deleting database 'itop'
> Trace: Info - CheckBackupPrerequisites
> Trace: Info - PHP functions disabled: 
> Info: mysqldump is present: Ok.
> Trace: Info - mysqldump -V said: mysqldump  Ver 10.19 Distrib 10.5.18-MariaDB, for debian-linux-gnu (x86_64)
> Error: The following modules have unmet dependencies: Configuration Management (CMDB) (id: itop-config-mgmt/3.0.2) depends on itop-structure/2.7.1, Service Management (id: itop-service-mgmt/3.0.2) depends on itop-tickets/2.0.0, Tickets Management (id: itop-tickets/3.0.2) depends on itop-structure/2.7.1
> Encountered stopper issues. Aborting...
> 

but with 2.7 its running but after we have

```
Fatal error: Uncaught Error: Class 'SetupUtils' not found in /var/www/html/application/forms.class.inc.php:1492
Stack trace:
  #0 /var/www/html/application/forms.class.inc.php(1456): RunTimeIconSelectionField::FindIconsOnDisk('/var/www/html/e...')
  #1 /var/www/html/core/modelreflection.class.inc.php(264): RunTimeIconSelectionField->__construct('icon', '', '') 
  #2 /var/www/html/application/dashlet.class.inc.php(1914): ModelReflectionRuntime->GetIconSelectionField('icon')
  #3 /var/www/html/application/dashboard.class.inc.php(185): DashletHeaderStatic->__construct(Object(ModelReflectionRuntime), '1')
  #4 /var/www/html/application/dashboard.class.inc.php(147): Dashboard->InitDashletFromDOMNode(Object(DOMElement))
  #5 /var/www/html/application/dashboard.class.inc.php(78): Dashboard->FromDOMDocument(Object(DOMDocument))
  #6 /var/www/html/application/dashboard.class.inc.php(883): Dashboard->FromXml('<?xml version="...')
  #7 /var/www/html/application/menunode.class.inc.php(1180): RuntimeDashboard::GetDashboard('/var/www/html/e...', 'Welco in /var/www/html/application/forms.class.inc.php on line 1492

iTop: An error occurred, check server error log for more information.
```

Once again, :2.6 image is fine

**Comment by Hipska** [comment]
Can you try to see the setup wizard works fine. Remember to select new installation instead of upgrade.

We cannot support unattended install as that is code delivered by Combodo, so issues regarding to that should be directed to their support portals.

**Comment by lazyest** [comment]
yeah, sure I've tried everything and I'll definitely not publish a post without this ;)
yes, I've tried new installation on both 2.7 and 3 images. Same docker-compose, 2.6 is OK, 2.7/3.0 failed

**Comment by Hipska** [comment]
I just ran the setup wizard with the following compose file and it all worked fine:
```yaml
version: '3'
services:
  itop:
    image: supervisions/itop:3.0
    environment:
      VIRTUAL_HOST: itop-test.docker.super-visions.com
      DB_ENV_MYSQL_DATABASE: itop
      DB_ENV_MYSQL_USER: itop
      DB_ENV_MYSQL_PASSWORD: itop
    links:
      - "db:db"
    network_mode: bridge
  db:
    image: mariadb
    environment:
      MYSQL_DATABASE: itop
      MYSQL_USER: itop
      MYSQL_PASSWORD: itop
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    network_mode: bridge
```

It also looks like your `itop-config.php` is not having a password anymore?
