### ISSUE TITLE
missing php file

### ISSUE THREAD

**Issue by fschiro** [Super-Visions/docker-itop#9]
I got this error in browser about a missing languages.php file:

```
Warning: require_once(/var/www/html/env-production/dictionaries/languages.php): failed to open stream: No such file or directory in /var/www/html/core/metamodel.class.php on line 6613

Fatal error: require_once(): Failed opening required '/var/www/html/env-production/dictionaries/languages.php' (include_path='/var/www/html/lib/pear/archive_tar:/var/www/html/lib/pear/console_getopt:/var/www/html/lib/pear/pear-core-minimal/src:/var/www/html/lib/pear/pear_exception:.:/usr/local/lib/php') in /var/www/html/core/metamodel.class.php on line 6613
```

Here is the docker-compose.yml:

```yaml
version: '3.9'

services:
  itop:
    image: supervisions/itop:latest
    container_name: my-itop
    ports:
      - "80:80"
    depends_on:
      - db
    volumes:
      - itop-data:/var/www/html
    environment:
      - MYSQL_HOST=db
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
      - MYSQL_DATABASE=itop

  db:
    image: mariadb
    container_name: my-itop-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=itop
      - MYSQL_USER=itop
      - MYSQL_PASSWORD=itop
    volumes:
      - db-data:/var/lib/mysql

volumes:
  itop-data:
```
